# This file is used as dynamicconfig override for "default" replication simulation scenario configured via host/testdata/replication_simulation_default.yaml

history.replicatorTaskBatchSize:
- value: 25
  constraints: {}
