#
# this is a copy of development.yaml, but with different ports for the services,
# and bootstrapping on development.yaml's service hosts.
#
# this is intended for running multiple instances locally, within the same cluster.
# start `--env development` first, then `--env development_instance2`.
#

persistence:
  defaultStore: cass-default
  visibilityStore: cass-visibility
  numHistoryShards: 4
  datastores:
    cass-default:
      nosql:
        pluginName: "cassandra"
        hosts: "127.0.0.1"
        keyspace: "cadence"
        connectTimeout: 2s # defaults to 2s if not defined
        timeout: 5s # defaults to 10s if not defined
        consistency: LOCAL_QUORUM # default value
        serialConsistency: LOCAL_SERIAL # default value
    cass-visibility:
      nosql:
        pluginName: "cassandra"
        hosts: "127.0.0.1"
        keyspace: "cadence_visibility"

ringpop:
  name: cadence
  bootstrapMode: hosts
  bootstrapHosts: [
    "127.0.0.1:7933", "127.0.0.1:7934", "127.0.0.1:7935",   # development.yaml list, for instance 1
    "127.0.0.1:27933", "127.0.0.1:27934", "127.0.0.1:27935" # for this instance
  ]
  maxJoinDuration: 30s

services:
  frontend:
    rpc:
      port: 27933
      grpcPort: 27833
      bindOnLocalHost: true
      grpcMaxMsgSize: 33554432
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 27936

  matching:
    rpc:
      port: 27935
      grpcPort: 27835
      bindOnLocalHost: true
      grpcMaxMsgSize: 33554432
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 27938

  history:
    rpc:
      port: 27934
      grpcPort: 27834
      bindOnLocalHost: true
      grpcMaxMsgSize: 33554432
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 27937

  worker:
    rpc:
      port: 27939
      bindOnLocalHost: true
    metrics:
      statsd:
        hostPort: "127.0.0.1:8125"
        prefix: "cadence"
    pprof:
      port: 27940

clusterGroupMetadata:
  failoverVersionIncrement: 10
  primaryClusterName: "cluster0"
  currentClusterName: "cluster0"
  clusterGroup:
    cluster0:
      enabled: true
      initialFailoverVersion: 0
      newInitialFailoverVersion: 1 # migrating to this new failover version
      rpcAddress: "localhost:7833" # this is to let worker service and XDC replicator connected to the frontend service. In cluster setup, localhost will not work
      rpcTransport: "grpc"

dcRedirectionPolicy:
  policy: "noop"
  toDC: ""

archival:
  history:
    status: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"
      gstorage:
        credentialsPath: "/tmp/gcloud/keyfile.json"
  visibility:
    status: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"

domainDefaults:
  archival:
    history:
      status: "enabled"
      URI: "file:///tmp/cadence_archival/development"
    visibility:
      status: "enabled"
      URI: "file:///tmp/cadence_vis_archival/development"

dynamicconfig:
  client: filebased
  configstore:
    pollInterval: "10s"
    updateRetryAttempts: 2
    FetchTimeout: "2s"
    UpdateTimeout: "2s"
  filebased:
    filepath: "config/dynamicconfig/development.yaml"
    pollInterval: "10s"

blobstore:
  filestore:
    outputDirectory: "/tmp/blobstore"
