version: "3.5"

services:
  cass1:
    container_name: cass1
    hostname: cass1
    image: cassandra:4.1.1
    ports:
      - "9042:9042"
    environment: &environment    # Declare and save environments variables into "environment"
      MAX_HEAP_SIZE: 256M
      HEAP_NEWSIZE: 128M
      CASSANDRA_SEEDS: "cass1,cass2"    # The first two nodes will be seeds
      CASSANDRA_CLUSTER_NAME: SolarSystem
      CASSANDRA_DC: Mars
      CASSANDRA_RACK: West
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 30s
      retries: 10
    networks:
      services-network:
        aliases:
          - integration-test

  cass2:
    container_name: cass2
    hostname: cass2
    image: cassandra:4.1.1
    ports:
      - "9043:9042"
    environment: *environment # point to "environment" to use the same environment variables as cass1
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 30s
      retries: 10
    networks:
      services-network:
        aliases:
          - integration-test

  test-cass-lwt:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command:
      - /bin/sh
      - -e
      - -c
      - >
        go test -timeout 180s
        -run ^TestCassandraLWT$
        -count 1
        -v
        -tags cassandralwt
        github.com/uber/cadence/host
        | tee test.log
    ports:
      - "7933:7933"
      - "7934:7934"
      - "7935:7935"
      - "7939:7939"
    environment:
      # - "CASSANDRA_HOST=cass1"
      - "CASSANDRA=1"
      - "CASSANDRA_SEEDS=cass1,cass2"
    depends_on:
      cass1:
        condition: service_healthy
      cass2:
        condition: service_healthy
    volumes:
      - ../../:/cadence
    networks:
      services-network:
        aliases:
          - integration-test

networks:
  services-network:
    name: services-network
    driver: bridge
